apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kafka-rest-demo
  name: kafka-rest-demo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        sidecar.opentelemetry.io/inject: "true"
      labels:
        app: kafka-rest-demo
    spec:
      containers:
      - image: emmettmoore/mystuff:kafka-rest-demo
        imagePullPolicy: IfNotPresent
        name: kafka-rest-demo-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30