apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: kafka-rest-demo
  name: kafka-rest-demo-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.12.105
  clusterIPs:
  - 10.108.12.105
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31656
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kafka-rest-demo
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.75.254.63